#!/usr/bin/env python3
"""
gen_matrix_font.py — Matrix Code rain font for Tramli boot animation.

Renders half-width katakana from MS Gothic into a monospace GFX font
mapped to the printable ASCII range (0x21–0x7E) so the rain animation
can pick glyphs with random(94) without any encoding changes.

Output: include/matrix_font.h
"""

from PIL import ImageFont, ImageDraw, Image
import os, sys

FONT_PATH  = "C:/Windows/Fonts/msgothic.ttc"
FONT_FACE  = 0       # face 0 = MS Gothic (monospace)
FONT_PX    = 16      # render size in pixels
OUT_PATH   = os.path.join(os.path.dirname(__file__), "../include/matrix_font.h")

FIRST_ASCII = 0x21   # '!'
LAST_ASCII  = 0x7E   # '~'
N           = LAST_ASCII - FIRST_ASCII + 1  # 94

# Half-width katakana U+FF66–FF9D (56 chars) are the visual core of the
# Matrix digital rain. Padded with digits and a few symbols to fill 94 slots.
_KATA = "ｦｧｨｩｪｫｬｭｮｯｰｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝ"
_DIGS = "0123456789"
_SYMS = "!#$%&=?+-*/:<>|@"
_SRC  = _KATA + _DIGS + _SYMS + _KATA   # longer than 94; we'll slice

GLYPHS_SRC = list(_SRC)[:N]             # exactly 94 source chars


def render_one(font, ch, ascent, descent, cell_w):
    """
    Render ch into a GFX glyph entry, horizontally centred in cell_w.
    Returns (packed_bytes, width, height, x_off, y_off) or ([], 0, 0, 0, 0).
    """
    y_advance = ascent + descent
    M = FONT_PX * 2                      # generous margin so nothing clips
    canvas_w = FONT_PX * 4
    canvas_h = y_advance + M * 2

    img  = Image.new('L', (canvas_w, canvas_h), 0)
    draw = ImageDraw.Draw(img)
    draw.text((M, M), ch, font=font, fill=255)

    pix  = img.load()
    minx = canvas_w;  maxx = -1
    miny = canvas_h;  maxy = -1
    for y in range(canvas_h):
        for x in range(canvas_w):
            if pix[x, y] > 64:
                if x < minx: minx = x
                if x > maxx: maxx = x
                if y < miny: miny = y
                if y > maxy: maxy = y

    if maxx < 0:
        return [], 0, 0, 0, 0

    w = maxx - minx + 1
    h = maxy - miny + 1

    # Centre ink horizontally within cell_w
    ink_w   = maxx - minx + 1
    x_shift = (cell_w - ink_w) // 2     # pixels to shift right for centering
    x_off   = (minx - M) + x_shift
    y_off   = miny - (M + ascent)       # negative = above baseline

    crop = img.crop((minx, miny, maxx + 1, maxy + 1))

    # Pack: MSB first, continuous bitstream (no per-row byte padding)
    packed    = []
    byte_val  = 0
    bit_count = 0
    for row in range(h):
        for col in range(w):
            if crop.getpixel((col, row)) > 64:
                byte_val |= (1 << (7 - bit_count))
            bit_count += 1
            if bit_count == 8:
                packed.append(byte_val)
                byte_val  = 0
                bit_count = 0
    if bit_count:
        packed.append(byte_val)

    return packed, w, h, x_off, y_off


def main():
    if not os.path.exists(FONT_PATH):
        print(f"ERROR: {FONT_PATH} not found")
        sys.exit(1)

    font = ImageFont.truetype(FONT_PATH, FONT_PX, index=FONT_FACE)
    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    # Measure actual advance of a representative half-width katakana glyph
    sample_adv = round(font.getlength("ｱ"))
    cell_w = sample_adv  # use the natural advance as the monospace cell width

    print(f"MS Gothic {FONT_PX}px: ascent={ascent} descent={descent} "
          f"yAdvance={y_advance} half-width-adv={sample_adv}")
    print(f"Grid on 480×222: {480 // cell_w} cols × {222 // y_advance} rows  "
          f"(cell {cell_w}×{y_advance}px)")

    bitmap_bytes = []
    glyphs       = []
    offset       = 0

    for i, ch in enumerate(GLYPHS_SRC):
        packed, w, h, x_off, y_off = render_one(font, ch, ascent, descent, cell_w)
        if not packed:
            glyphs.append((offset, 0, 0, cell_w, 0, 0))
        else:
            bitmap_bytes.extend(packed)
            glyphs.append((offset, w, h, cell_w, x_off, y_off))
            offset += len(packed)

    lines = [
        "// AUTO-GENERATED by scripts/gen_matrix_font.py — do not edit by hand",
        "// Run:  python scripts/gen_matrix_font.py",
        "#pragma once",
        '#include <Arduino_GFX_Library.h>',
        "",
        f"// Half-width katakana from MS Gothic {FONT_PX}px, monospace {cell_w}×{y_advance}px",
        f"// Grid: {480 // cell_w} cols × {222 // y_advance} rows on 480×222",
        f"#define MATRIX_FONT_W    {cell_w}",
        f"#define MATRIX_FONT_H    {y_advance}",
        f"#define MATRIX_FONT_ASC  {ascent}",
        "",
        "static const uint8_t MatrixCodeBitmaps[] PROGMEM = {",
    ]
    row = []
    for i, b in enumerate(bitmap_bytes):
        row.append(f"0x{b:02X}")
        if len(row) == 16 or i == len(bitmap_bytes) - 1:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    lines.append("")
    lines.append("static const GFXglyph MatrixCodeGlyphs[] PROGMEM = {")
    for i, (off, w, h, xadv, xoff, yoff) in enumerate(glyphs):
        ch = GLYPHS_SRC[i]
        lines.append(f"  {{{off:6}, {w:3}, {h:3}, {xadv:3}, {xoff:4}, {yoff:4} }},  // {ch}")
    lines.append("};")
    lines.append("")
    lines.append("static const GFXfont MatrixCode PROGMEM = {")
    lines.append("  (uint8_t *)MatrixCodeBitmaps,")
    lines.append("  (GFXglyph *)MatrixCodeGlyphs,")
    lines.append(f"  0x{FIRST_ASCII:02X}, 0x{LAST_ASCII:02X}, {y_advance}")
    lines.append("};")
    lines.append(f"// MatrixCode: ascent={ascent}, yAdvance={y_advance}, "
                 f"bitmaps={len(bitmap_bytes)} bytes")
    lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}  ({len(bitmap_bytes)} bitmap bytes)")


if __name__ == "__main__":
    main()
