#!/usr/bin/env python3
# gen_stops.py — Generate include/swiss_stops.h from a Swiss GTFS stops.txt
#
# Usage:
#   python scripts/gen_stops.py path/to/stops.txt
#
# Where to get stops.txt:
#   1. Go to https://opentransportdata.swiss/en/dataset/timetable-2025-gtfs2020
#   2. Download the GTFS ZIP (you need a free account)
#   3. Unzip and locate stops.txt inside
#
# The script extracts parent station names (location_type=1) plus standalone
# stops (location_type=0 with no parent_station), deduplicates, sorts, and
# writes a C header file suitable for PROGMEM / flash storage on ESP32.

import csv
import sys
import os

def main():
    if len(sys.argv) < 2:
        print("Usage: python gen_stops.py path/to/stops.txt")
        sys.exit(1)

    stops_file = sys.argv[1]
    out_file   = os.path.join(os.path.dirname(__file__), "..", "include", "swiss_stops.h")

    names = set()
    rows_read = 0

    with open(stops_file, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows_read += 1
            loc_type = row.get("location_type", "").strip()
            name     = row.get("stop_name",     "").strip()
            parent   = row.get("parent_station", "").strip()

            if not name:
                continue

            # Include parent stations and standalone stops (no parent assigned)
            if loc_type == "1" or (loc_type in ("", "0") and not parent):
                names.add(name)

    names_sorted = sorted(names, key=lambda s: s.lower())
    count = len(names_sorted)
    print(f"Read {rows_read} rows → {count} unique station names")

    with open(out_file, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Auto-generated by scripts/gen_stops.py — do not edit manually\n")
        f.write("// Source: Swiss GTFS stops.txt from opentransportdata.swiss\n")
        f.write(f"// {count} unique station names, stored in flash (no RAM cost)\n")
        f.write("#pragma once\n\n")
        f.write(f"static const int SWISS_STOPS_COUNT = {count};\n\n")
        f.write("static const char* const SWISS_STOPS[] = {\n")
        for name in names_sorted:
            escaped = name.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'    "{escaped}",\n')
        f.write("};\n")

    print(f"Written → {os.path.abspath(out_file)}")

if __name__ == "__main__":
    main()
