#!/usr/bin/env python3
"""
gen_fonts.py — Generate GFX bitmap font headers for Tramli.

Renders two sizes of Arial Bold and writes a GFX font header:
  TramliSmall  (~14 px, replaces setTextSize(2))
  TramliLarge  (~22 px, replaces setTextSize(3))

Coverage: 0x20-0xFF (Latin-1, covering ä ö ü Ä Ö Ü é è à etc.)
Output:   include/tramli_fonts.h
"""

from PIL import ImageFont, ImageDraw, Image
import os, sys

FONT_PATH  = "C:/Windows/Fonts/arialbd.ttf"
OUT_PATH   = os.path.join(os.path.dirname(__file__), "../include/tramli_fonts.h")

FIRST_CHAR = 0x20
LAST_CHAR  = 0xFF

SIZES = [
    ("TramliSmall",  16),
    ("TramliLarge",  24),
    ("TramliXLarge", 28),
]


def render_font(ttf_path, px_size):
    font    = ImageFont.truetype(ttf_path, px_size)
    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    # Canvas big enough for any glyph, with generous margin so nothing clips
    MARGIN = px_size
    canvas_w = px_size * 6
    canvas_h = y_advance + MARGIN * 2

    bitmap_bytes = []
    glyphs       = []
    offset       = 0

    for cp in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(cp)

        # C1 control codes (0x80-0x9F) — placeholder with zero bitmap
        if 0x80 <= cp <= 0x9F:
            glyphs.append((offset, 0, 0, 4, 0, 0))
            continue

        # Render on a blank canvas, anchor at top-left of em square
        img  = Image.new('L', (canvas_w, canvas_h), 0)
        draw = ImageDraw.Draw(img)
        draw.text((MARGIN, MARGIN), ch, font=font, fill=255)

        # Scan for actual ink pixels
        pix   = img.load()
        min_x = canvas_w;  max_x = -1
        min_y = canvas_h;  max_y = -1
        for y in range(canvas_h):
            for x in range(canvas_w):
                if pix[x, y] > 64:
                    if x < min_x: min_x = x
                    if x > max_x: max_x = x
                    if y < min_y: min_y = y
                    if y > max_y: max_y = y

        if max_x < 0:
            # No ink — whitespace/invisible glyph
            adv = round(font.getlength(ch))
            glyphs.append((offset, 0, 0, max(adv, 1), 0, 0))
            continue

        w = max_x - min_x + 1
        h = max_y - min_y + 1

        # Crop to ink bounding box
        glyph_img = img.crop((min_x, min_y, max_x + 1, max_y + 1))

        # Pack bits: MSB first, continuous stream across all rows (no per-row padding).
        # Arduino_GFX reads glyph bitmaps as one unbroken bitstream — it never
        # resets the bit offset between rows — so per-row byte padding would shift
        # every subsequent row left and produce a shadow/double artifact.
        packed    = []
        byte_val  = 0
        bit_count = 0
        for row in range(h):
            for col in range(w):
                if glyph_img.getpixel((col, row)) > 64:
                    byte_val |= (1 << (7 - bit_count))
                bit_count += 1
                if bit_count == 8:
                    packed.append(byte_val)
                    byte_val  = 0
                    bit_count = 0
        if bit_count:
            packed.append(byte_val)

        # x_off: ink left edge relative to the pen (MARGIN = pen x)
        # y_off: ink top edge relative to the baseline (MARGIN+ascent = baseline y)
        x_adv = round(font.getlength(ch))
        x_off = min_x - MARGIN
        y_off = min_y - (MARGIN + ascent)   # negative → above baseline

        bitmap_bytes.extend(packed)
        glyphs.append((offset, w, h, x_adv, x_off, y_off))
        offset += len(packed)

    return bitmap_bytes, glyphs, y_advance, ascent


def write_header(out_path, fonts):
    lines = [
        "// AUTO-GENERATED by scripts/gen_fonts.py — do not edit by hand",
        "// Run:  python scripts/gen_fonts.py",
        "#pragma once",
        '#include <Arduino_GFX_Library.h>',
        "",
    ]

    for name, bitmaps, glyphs, y_adv, ascent in fonts:
        # Bitmap array
        lines.append(f"static const uint8_t {name}Bitmaps[] PROGMEM = {{")
        row = []
        for i, b in enumerate(bitmaps):
            row.append(f"0x{b:02X}")
            if len(row) == 16 or i == len(bitmaps) - 1:
                lines.append("  " + ", ".join(row) + ",")
                row = []
        lines.append("};")
        lines.append("")

        # Glyph table
        lines.append(f"static const GFXglyph {name}Glyphs[] PROGMEM = {{")
        for i, (off, w, h, xadv, xoff, yoff) in enumerate(glyphs):
            cp = FIRST_CHAR + i
            label = f"0x{cp:02X}"
            if 0x20 <= cp <= 0x7E:
                label += f" '{chr(cp)}'"
            lines.append(f"  {{{off:6}, {w:3}, {h:3}, {xadv:3}, {xoff:4}, {yoff:4} }},  // {label}")
        lines.append("};")
        lines.append("")

        # Font struct
        lines.append(f"static const GFXfont {name} PROGMEM = {{")
        lines.append(f"  (uint8_t *){name}Bitmaps,")
        lines.append(f"  (GFXglyph *){name}Glyphs,")
        lines.append(f"  0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X}, {y_adv}")
        lines.append("};")
        lines.append(f"// {name}: ascent={ascent}, yAdvance={y_adv}, "
                     f"bitmaps={len(bitmaps)} bytes")
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    if not os.path.exists(FONT_PATH):
        print(f"ERROR: font not found: {FONT_PATH}")
        sys.exit(1)

    # Quick sanity-check: print ink range for 'H' and 'g'
    for name, px in SIZES:
        font = ImageFont.truetype(FONT_PATH, px)
        asc, desc = font.getmetrics()
        print(f"\n{name} ({px}px): ascent={asc}, descent={desc}, yAdvance={asc+desc}")
        for ch in ('H', 'g', 'ä'):
            M = px
            img = Image.new('L', (px*6, asc+desc+M*2), 0)
            ImageDraw.Draw(img).text((M, M), ch, font=font, fill=255)
            pix = img.load()
            ys = [y for y in range(img.height) for x in range(img.width) if pix[x,y] > 64]
            if ys:
                print(f"  '{ch}': ink y=[{min(ys)}, {max(ys)}]  "
                      f"baseline at {M+asc}  "
                      f"yoff={min(ys)-(M+asc)}")

    rendered = []
    for name, px in SIZES:
        print(f"\nRendering {name} at {px}px ...")
        bitmaps, glyphs, y_adv, ascent = render_font(FONT_PATH, px)
        rendered.append((name, bitmaps, glyphs, y_adv, ascent))
        non_empty = sum(1 for g in glyphs if g[1] > 0)
        print(f"  {len(bitmaps)} bitmap bytes, {non_empty} non-empty glyphs")

    write_header(OUT_PATH, rendered)
